name: Fetch and Post Truths

on:
  schedule:
    - cron: '*/5 9-23 * * 1-5'  # Every 5 minutes, Mon–Fri (UTC)
  workflow_dispatch:  # Allow manual runs

jobs:
  post-truths:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Required to push changes

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python fetch_truth_social.py

    - name: Commit and push posted log
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add posted_truths.json
        git commit -m "Update posted_truths.json" || echo "No changes to commit"
        git push

