name: Fetch and Post News

on:
  schedule:
    # From 5 AM to 11:30 PM ET (i.e., 09:00 to 23:30 UTC) on weekdays
    - cron: '*/30 8-23 * * 1-5'
    # From 12:00 AM to 2:30 AM ET (i.e., 00:00 to 2:30 UTC) on weekdays
    - cron: '*/30 0-2 * * 2-6'
  workflow_dispatch: # Allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch_news.py
        run: python fetch_news.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

