name: Fetch High Impact News

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stash uncommitted changes before pulling
        run: |
          git stash push --include-untracked --message "Auto stash before rebase"
          git pull --rebase origin main || true
          git stash pop || true

      - name: Commit changes if any
        run: |
          git add high_impact_news.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto update high impact news"
            git push origin main
          fi



