name: Update High Impact News

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:       # allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run fetch_news.py
      run: python fetch_news.py

    - name: Configure git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add high_impact_news.json

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto update high impact news"
        fi

        # Stash any unstaged changes before pull
        git stash --include-untracked

        git pull --rebase origin main

        # Re-apply stashed changes (if any)
        git stash pop || echo "No stash to apply"

        git push origin main



