name: Fetch High Impact News

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: indicator

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stash uncommitted changes before pulling
        run: |
          git stash push --include-untracked --message "Auto stash before rebase"
          git pull --rebase origin main || true
          git stash pop || true

      - name: Push changes using PAT
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main




