name: Update High Impact News

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest changes (rebase)
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git stash push --include-untracked -m "auto-stash"
          git pull --rebase origin main
          git stash pop || true

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install feedparser
        run: pip install feedparser

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Commit updated high_impact_news.json if needed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          if git status --porcelain | grep -q high_impact_news.json; then
            git add high_impact_news.json
            git commit -m "Update high_impact_news.json [skip ci]"
            git push origin main
          else
            echo "No changes to high_impact_news.json"
          fi




